version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: asu-management-mysql
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_NAME:-management_system}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - asu_management_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # NestJS Backend Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asu-management-api
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file: .env
    volumes:
      - /app/node_modules
    depends_on:
      - mysql
      - minio

  # Database Backup Service
  db-backup:
    image: arm64v8/phpmyadmin
    # image: phpmyadmin/phpmyadmin
    container_name: asu-management-db-backup
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    volumes:
      - asu_management_db_backups:/backup
    environment:
      - PMA_HOST=${DB_HOST:-mysql}
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    depends_on:
      - mysql

  # MinIO Service
  minio:
    image: minio/minio
    container_name: asu-management-minio
    restart: always
    ports:
      - "${MINIO_PORT:-9000}:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - asu_management_minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  asu_management_mysql_data:
  asu_management_db_backups:
  asu_management_minio_data: