version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: asu-management-mysql
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME:-management_system}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - asu_management_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD:-root}"]
      timeout: 20s
      retries: 10

  # NestJS Backend Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asu-management-api
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file: .env
    volumes:
      - /app/node_modules
    depends_on:
      - mysql
      - minio

  # PhpMyAdmin client
  phpmyadmin:
    image: arm64v8/phpmyadmin
    #image: phpmyadmin/phpmyadmin
    container_name: asu-management-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      VIRTUAL_HOST: asu-phpmyadmin.zeyadhekal.tech
      VIRTUAL_PORT: 80
      PMA_ABSOLUTE_URI: https://asu-phpmyadmin.zeyadhekal.tech/
    ports:
      - "${DB_PHPMYADMIN_PORT:-4004}:80"
    depends_on:
      mysql:
        condition: service_healthy

  # Database Backup Service
  db-backup:
    build:
      context: .
      dockerfile: Dockerfile.db_backup
    container_name: asu-management-db-backup
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_NAME:-management_system}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    volumes:
      - asu_management_db_backups:/backups
    depends_on:
      mysql:
        condition: service_healthy

  # MinIO Service
  minio:
    image: minio/minio
    container_name: asu-management-minio
    restart: always
    ports:
      - "${MINIO_INTERNAL_PORT:-9000}:9000"
      - "${MINIO_DASHBOARD_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - asu_management_minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  asu_management_mysql_data:
  asu_management_db_backups:
  asu_management_minio_data: